language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  - DEPS=lowest
  - DEPS=latest

before_script:
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-stable --no-interaction --prefer-lowest ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --prefer-stable --no-interaction ; fi

script:
  - ./vendor/bin/phpunit
